version: "3"
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    container_name: test_app
    ports:
      - "8080:8080"
    environment:
      CMD_ENV: production
    depends_on:
      - db
  db:
    image: mysql:8.0.33
    container_name: test_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  mysql_data:
